image: debian:openssl-build

stages:
    - build         # contains build and test and deploy

linux-x86_64:
    script:
        - git submodule update --init
        - mkdir build
        - cd build
        - cmake ../ -DPREBUILT_BRANCH=x86_64-linux
        - make
        - test/AllUnitTests             # runs gtest target
        - make Coverage                 # generate code coverage
    stage: build
    only:
        - master
    artifacts:
        paths:
        - build/test/coverage/           # coverage data
