image: debian:openssl-build

stages:
    - build         # contains build and test and deploy

variables:
    OPENSSL_BRANCH: "OpenSSL_1_0_2d"
    
linux-x86_64:
    script:
        - git submodule update --init
        - mkdir build
        - cd build
        - cmake ../ -DOPENSSL_BRANCH=$OPENSSL_BRANCH -DPREBUILT_BRANCH=x86_64-linux
        - make
        - test/AllUnitTests             # runs gtest target
    stage: build
    only:
        - master
